// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class AdvertisingBlock
    {
        public AdvertisingBlock()
        {
            Advertising = new HashSet<Advertising>();
        }

        public int AdvertisingBlock_ID { get; set; }
        public int? ArticleCategory_ID { get; set; }
        public int? Position { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool? Active { get; set; }
        public Guid? CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public Guid? LastEditedBy { get; set; }
        public DateTime? LastEditedDate { get; set; }
        public bool? IsMobile { get; set; }
        public bool? Lock { get; set; }
        public int? JssorSlide_ID { get; set; }
        public int? TimingSlide { get; set; }
        public string SizeSuggest { get; set; }

        public virtual ICollection<Advertising> Advertising { get; set; }
    }
}