// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ArticleVoice
    {
        public int ArticleVoice_ID { get; set; }
        public string FileName { get; set; }
        public string FileUrl { get; set; }
        public string LinkAPI { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? LastUpdateDate { get; set; }
        public int? Article_ID { get; set; }
        public int? Sort { get; set; }
    }
}