// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ArticleType
    {
        public int ArticleType_ID { get; set; }
        public string Name { get; set; }
    }
}