// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ArticleVoiceType
    {
        public int ArticleVoiceType_ID { get; set; }
        public string VoiceName { get; set; }
        public string VoiceKey { get; set; }
        public string VoiceNameCode { get; set; }
        public string Rate { get; set; }
        public int? Service_Type { get; set; }
    }
}