// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ArticleCategoryArticle
    {
        public int ArticleCategoryArticle_ID { get; set; }
        public int? ArticleCategory_ID { get; set; }
        public int? Article_ID { get; set; }
    }
}