// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ArticleBlockArticle
    {
        public int ArticleBlockArticle_id { get; set; }
        public int ArticleBlock_id { get; set; }
        public int Article_id { get; set; }

        public virtual ArticleBlock ArticleBlock_ { get; set; }
    }
}