// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ArticleComment
    {
        public int ArticleComment_ID { get; set; }
        public int? Article_ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public bool? Active { get; set; }
        public DateTime? CreateDate { get; set; }
    }
}