// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class AspNetUserProfiles
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        /// <summary>
        /// 1 là email, 2 là sdt
        /// </summary>
        public string RegType { get; set; }
        public DateTime? RegisterDate { get; set; }
        public bool? Verified { get; set; }
        public DateTime? VerifiedDate { get; set; }
        public DateTime? LastActivityDate { get; set; }
        public string FullName { get; set; }
        /// <summary>
        /// true là nam, false là nữ
        /// </summary>
        public bool? Gender { get; set; }
        public DateTime? BirthDate { get; set; }
        public string Company { get; set; }
        public int? ProductBrand_ID { get; set; }
        public int? Rank { get; set; }
        public string Address { get; set; }
        public int? Location_ID { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string FacebookID { get; set; }
        public string Skype { get; set; }
        public string AvatarUrl { get; set; }
        public string Signature { get; set; }
        public int? AccountType { get; set; }
        public int? CountryId { get; set; }
        public string ResumeProfilerContent { get; set; }
        public string WorkPosition { get; set; }
        public string Department { get; set; }
        public string FormOfLabor { get; set; }
        public string DirectManagement { get; set; }
        public string Subordinates { get; set; }
        public string ReferralAccountCode { get; set; }
    }
}