// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class Country
    {
        public int Country_ID { get; set; }
        public string Name { get; set; }
        public int? Sort { get; set; }
        public string CountryCode { get; set; }
        public string UrlFlag { get; set; }
    }
}