// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class Customer
    {
        public int Customer_ID { get; set; }
        public int? ProductBrand_ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string AboutUs { get; set; }
        public string Keyword { get; set; }
        public string Logo { get; set; }
        public string Address { get; set; }
        public int? Location_ID { get; set; }
        public string Map { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string YM { get; set; }
        public string Skype { get; set; }
        public string Website { get; set; }
        public string Contact { get; set; }
        public int? Rank { get; set; }
        public int? Counter { get; set; }
        public Guid? CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public Guid? LastEditBy { get; set; }
        public DateTime? LastEditDate { get; set; }
        public string URL { get; set; }
        public string Tag { get; set; }
    }
}