// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class DeliveryAddress
    {
        public int Id { get; set; }
        public Guid? UserId { get; set; }
        public string UserName { get; set; }
        public string PhoneNumber { get; set; }
        public int? LocationId { get; set; }
        public int? DistrictId { get; set; }
        public string Address { get; set; }
        public bool? IsDefault { get; set; }
        public DateTime? CreateDate { get; set; }
        public Guid? CreateBy { get; set; }
        public DateTime? LastEditDate { get; set; }
        public Guid? LastEditBy { get; set; }
    }
}