// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class DepartmentMan
    {
        public int DepartmentMan_ID { get; set; }
        public int? Parent_ID { get; set; }
        public string Name { get; set; }
        public int? Sort { get; set; }
    }
}