// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class Department
    {
        public int Department_ID { get; set; }
        public int? Language_ID { get; set; }
        public string Name { get; set; }
        public string Leader { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
    }
}