// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class Email
    {
        public int Email_ID { get; set; }
        public int? Article_ID { get; set; }
        public Guid? UserId { get; set; }
        public string FromName { get; set; }
        public string ToName { get; set; }
        public string ToEmail { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public DateTime? CreateDate { get; set; }
        public bool? Sent { get; set; }
        public DateTime? SendDate { get; set; }
    }
}