// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class FCMMessageForTokken
    {
        public int FCMMessageForTokken_ID { get; set; }
        public int FCMMessage_ID { get; set; }
        public Guid? UserID { get; set; }
        public Guid? CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
    }
}