// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class FCMMessage
    {
        public int FCMMessage_ID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string Content { get; set; }
        public Guid? CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public Guid? LastEditBy { get; set; }
        public DateTime? LastEditDate { get; set; }
        public string AuthorizationKey { get; set; }
        public string Sender_ID { get; set; }
        public string UserName { get; set; }
        public Guid? UserID { get; set; }
        public string Topic { get; set; }
        public int? NotificationType { get; set; }
        public string Form_ID { get; set; }
        public int? ParameterId { get; set; }
        public string FullUrl { get; set; }
        public string FullUrlImage { get; set; }
        public int? HasRead { get; set; }
        public int? HasSent { get; set; }
        public int? NotiSpecType { get; set; }
        public int? IsPinTop { get; set; }
        public string FormNameApp { get; set; }
        public int? ProductTypeId { get; set; }
        public int? CategoryId { get; set; }
        public string OrderId { get; set; }
        public string OrderCode { get; set; }
    }
}