// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class GoldPrice
    {
        public int GoldPrice_ID { get; set; }
        public string Name { get; set; }
        public decimal? Buy { get; set; }
        public decimal? Sell { get; set; }
    }
}