// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class GoogleIndexSetting
    {
        public int Id { get; set; }
        public string Accept { get; set; }
        public string Cookie { get; set; }
        public string XClientData { get; set; }
    }
}