// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class HighLightProduct
    {
        public int Id { get; set; }
        public int? CategoryId { get; set; }
        public int? ProductId { get; set; }
        public int? ChildCate { get; set; }
        public int? ProductTypeId { get; set; }
        public string ProductName { get; set; }
        public int? Sort { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? LastEditedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? LastEditedBy { get; set; }
        public bool? Active { get; set; }
    }
}