// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class Language
    {
        public Language()
        {
            ProductCategory = new HashSet<ProductCategory>();
            SettingDefaultLanguage_ = new HashSet<Setting>();
            SettingDefaultSkin_ = new HashSet<Setting>();
        }

        public int Language_ID { get; set; }
        public string Name { get; set; }
        public int? Skin_ID { get; set; }
        public string Charset { get; set; }
        public string Culture { get; set; }
        public string URL { get; set; }
        public int? Article_Top { get; set; }
        public string WebsiteName { get; set; }
        public string Keyword { get; set; }
        public string Description { get; set; }
        public bool? Active { get; set; }
        public int? Sort { get; set; }

        public virtual ICollection<ProductCategory> ProductCategory { get; set; }
        public virtual ICollection<Setting> SettingDefaultLanguage_ { get; set; }
        public virtual ICollection<Setting> SettingDefaultSkin_ { get; set; }
    }
}