// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class LogAPI
    {
        public int Id { get; set; }
        public DateTime? Date { get; set; }
        public string ResponseMillis { get; set; }
        public string StatusCode { get; set; }
        public string Method { get; set; }
        public string Path { get; set; }
        public string QueryString { get; set; }
        public string RequestBody { get; set; }
        public string ResponseBody { get; set; }
        public string UserId { get; set; }
    }
}