// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class MetaKeyword
    {
        public int MetaKeyword_ID { get; set; }
        public int? ProductCategory_ID { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public string Type { get; set; }
    }
}