// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class MetaResume
    {
        public int MetaResume_ID { get; set; }
        public Guid? Resume_ID { get; set; }
        public Guid? User_ID { get; set; }
        public int? ResumeCategory_ID { get; set; }
        public Guid? CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public Guid? LastEditedBy { get; set; }
        public DateTime? LastEditedDate { get; set; }
    }
}