// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class Minor
    {
        public int MinorID { get; set; }
        public int? MajorID { get; set; }
        public string MinorName { get; set; }
    }
}