// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class PageLayout
    {
        public int Id { get; set; }
        public int? Page_ID { get; set; }
        public int? Position { get; set; }
        public bool? Active { get; set; }
        public int? Lock { get; set; }
        public string AreaName { get; set; }
        public string AreaTitle { get; set; }
        public string AreaIdentity { get; set; }
        public string Setting { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? ModifieldOn { get; set; }
        public string URL_GET { get; set; }
        public int? ProductCategoryId { get; set; }
    }
}