// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class PhoneList
    {
        public int Id { get; set; }
        public string PhoneNumber { get; set; }
        public bool? PHoneStatus { get; set; }
    }
}