// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ProductBrandCategory
    {
        public int ProductBrandCategory_ID { get; set; }
        public int? ProductBrand_ID { get; set; }
        public int? ProductCategory_ID { get; set; }
    }
}