// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ProductPropertyCategory
    {
        public ProductPropertyCategory()
        {
            ProductProperty = new HashSet<ProductProperty>();
        }

        public int ProductPropertyCategory_ID { get; set; }
        public int ProductCategory_ID { get; set; }
        public string Name { get; set; }
        public int? Sort { get; set; }

        public virtual ProductCategory ProductCategory_ { get; set; }
        public virtual ICollection<ProductProperty> ProductProperty { get; set; }
    }
}