// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ProductProperty
    {
        public ProductProperty()
        {
            ProductSearchCriteria = new HashSet<ProductSearchCriteria>();
        }

        public int ProductProperty_ID { get; set; }
        public int? ProductPropertyCategory_ID { get; set; }
        public int? ProductPropertyType_ID { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public int? Sort { get; set; }

        public virtual ProductPropertyCategory ProductPropertyCategory_ { get; set; }
        public virtual ProductPropertyType ProductPropertyType_ { get; set; }
        public virtual ICollection<ProductSearchCriteria> ProductSearchCriteria { get; set; }
    }
}