// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ProductBrand
    {
        public int ProductBrand_ID { get; set; }
        public int? Country_ID { get; set; }
        public int? Location_ID { get; set; }
        public int? ProductBrandType_ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string TradingName { get; set; }
        public string BrandName { get; set; }
        public string TaxCode { get; set; }
        public string RegistrationNumber { get; set; }
        public DateTime? IssuedDate { get; set; }
        public string BusinessArea { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public string PostalCode { get; set; }
        public string MapCode { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public bool EmailDisplay { get; set; }
        public string Website { get; set; }
        public string Facebook { get; set; }
        public string Zalo { get; set; }
        public string Hotline { get; set; }
        public string Skype { get; set; }
        public string PRInfo { get; set; }
        public string Agency { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string PersonName { get; set; }
        public string PersonAddress { get; set; }
        public string PersonMobile { get; set; }
        public string PersonEmail { get; set; }
        public string DirectorName { get; set; }
        public DateTime? DirectorBirthday { get; set; }
        public string DirectorAddress { get; set; }
        public string DirectorMobile { get; set; }
        public string DirectorEmail { get; set; }
        public string DirectorPosition { get; set; }
        public string URL { get; set; }
        public bool? Active { get; set; }
        public bool? Verified { get; set; }
        public int? Rank { get; set; }
        public int? ViewCount { get; set; }
        public Guid? CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public Guid? LastEditBy { get; set; }
        public DateTime? LastEditDate { get; set; }
        public string Logo { get; set; }
        public string Banner { get; set; }
        public string ReferralCode { get; set; }
        public int? NumberOfNotification { get; set; }
        public DateTime? ReferralCodeDate { get; set; }
    }
}