// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ProductRenew
    {
        public int Id { get; set; }
        public int ProductBrand_ID { get; set; }
        public DateTime? DateRenew { get; set; }
        public int? Product_Id { get; set; }
        public int? RenewCount { get; set; }
        public string Remark { get; set; }
        public Guid? CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public Guid? LastEditBy { get; set; }
        public DateTime? LastEditDate { get; set; }
    }
}