// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ProductTop
    {
        public int ProductTop_ID { get; set; }
        public int? ProductCategory_ID { get; set; }
        public int? Product_ID { get; set; }
        public DateTime? DateCreate { get; set; }
    }
}