// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class Product
    {
        public int Product_ID { get; set; }
        public int? Store_ID { get; set; }
        public int? ProductCategory_ID { get; set; }
        public int? ProductCategoryMachine_ID { get; set; }
        public int? ProductType_ID { get; set; }
        public int? ProductBrand_ID { get; set; }
        public int? ProductModel_ID { get; set; }
        public int? ProductManufacture_ID { get; set; }
        public int? Country_ID { get; set; }
        public string BarCode { get; set; }
        public string QRCodePublic { get; set; }
        public string Name { get; set; }
        public string ProductNotation { get; set; }
        public string PartNumber { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string PRInfo { get; set; }
        public string LegalInfo { get; set; }
        public string Image { get; set; }
        public string BannerImages { get; set; }
        public decimal? Price { get; set; }
        public decimal? PriceOld { get; set; }
        public decimal? Discount { get; set; }
        public int? DiscountRate { get; set; }
        public bool? IsSecondHand { get; set; }
        public bool? IsAuthor { get; set; }
        public bool? IsBestSale { get; set; }
        public bool? IsSaleOff { get; set; }
        public bool? IsNew { get; set; }
        public bool? IsComming { get; set; }
        public bool? IsOutStock { get; set; }
        public bool? IsDiscontinue { get; set; }
        public string Unit { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public DateTime? CreateDate { get; set; }
        public Guid? CreateBy { get; set; }
        public DateTime? LastEditDate { get; set; }
        public Guid? LastEditBy { get; set; }
        public int? Status { get; set; }
        public bool? Active { get; set; }
        public int? Counter { get; set; }
        public int? ViewCount { get; set; }
        public int? SellCount { get; set; }
        public string URL { get; set; }
        public string FullURL { get; set; }
        public string Alias { get; set; }
        public string Tag { get; set; }
        public string Keyword { get; set; }
        public bool? AllowComment { get; set; }
        public string Expiry { get; set; }
        public int? ExpiryByDate { get; set; }
        public int? WarrantyMonth { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeywords { get; set; }
        public string SaleName { get; set; }
        public string SaleContactName { get; set; }
        public string SalePhone { get; set; }
        public string SaleAddress { get; set; }
        public int? SaleLocation_ID { get; set; }
        public string SaleEmail { get; set; }
        public string SerialNumber { get; set; }
        public int? YearManufacture { get; set; }
        public string StatusMachine { get; set; }
        public int? HoursOfWork { get; set; }
        public bool? AirConditioning { get; set; }
        public string EngineModel { get; set; }
        public string EngineManufacture { get; set; }
        public string RentalPeriod { get; set; }
        public string RentalType { get; set; }
        public string WorkingAddress { get; set; }
        public int? WorkingLocation_ID { get; set; }
        public string PaymentlType { get; set; }
        public int? Job1Flag { get; set; }
        public int? StatusType_ID { get; set; }
        public string MetaKeywordIds { get; set; }
        public string AccessoriesModelName { get; set; }
        public int? AccessoriesCategoryId { get; set; }
        public int? AccessoriesManufactureId { get; set; }
        public int? AmountUnit { get; set; }
        public int? LengthSize { get; set; }
        public int? WidthSize { get; set; }
        public int? HeightSize { get; set; }
        public string PackInfo { get; set; }
        public string AccessoriesTypeName { get; set; }
        public string AccessoriesManufactureName { get; set; }
        public string SizeInfo { get; set; }
        public string Label { get; set; }
        public int? MaterialCategoryId { get; set; }
        public string MaterialManufactureName { get; set; }
        public bool? HasNewModel { get; set; }
        public int? RelatedCategoryId { get; set; }
        public string ReferralCode { get; set; }
        public string SKU { get; set; }
        public string SalePhoneStore { get; set; }
        public int? MadeCountryId { get; set; }
        public int? HourOfWorkType { get; set; }
    }
}