// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ProductOrderDetails
    {
        public int ProductOrderDetails_ID { get; set; }
        public int? ProductOrder_ID { get; set; }
        public int? Product_ID { get; set; }
        public int? Quatity { get; set; }
        public decimal? Price { get; set; }

        public virtual ProductOrder ProductOrder_ { get; set; }
    }
}