// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ProductOrderStatus
    {
        public ProductOrderStatus()
        {
            ProductOrder = new HashSet<ProductOrder>();
        }

        public int ProductOrderStatus_ID { get; set; }
        public string Name { get; set; }
        public int? Language_ID { get; set; }

        public virtual ICollection<ProductOrder> ProductOrder { get; set; }
    }
}