// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ProductOrder
    {
        public ProductOrder()
        {
            ProductOrderDetails = new HashSet<ProductOrderDetails>();
        }

        public int ProductOrder_ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Time { get; set; }
        public string MoreInfo { get; set; }
        public int? ProductOrderStatus_ID { get; set; }
        public Guid? CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public Guid? LastEditBy { get; set; }
        public DateTime? LastEditDate { get; set; }
        public decimal? DisCount { get; set; }

        public virtual ProductOrderStatus ProductOrderStatus_ { get; set; }
        public virtual ICollection<ProductOrderDetails> ProductOrderDetails { get; set; }
    }
}