// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ProductBrandBlockProductBrand
    {
        public int ProductBrandBlockProductBrand_id { get; set; }
        public int ProductBrandBlock_id { get; set; }
        public int ProductBrand_id { get; set; }
        public Guid? CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public Guid? LastEditBy { get; set; }
        public DateTime? LastEditDate { get; set; }
    }
}