// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ProductModel
    {
        public int ProductModel_ID { get; set; }
        public int? ProductManufacture_ID { get; set; }
        public int? ProductCategory_ID { get; set; }
        public string Name { get; set; }
        public string NamePart1 { get; set; }
        public int? NamePart2 { get; set; }
        public string NamePart3 { get; set; }
        public string Website { get; set; }
        public string URL { get; set; }
        public Guid? CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public Guid? LastEditBy { get; set; }
        public DateTime? LastEditDate { get; set; }
        public bool? IsEnable { get; set; }
        /// <summary>
        /// 1: mới thêm chưa duyệt, 2: đã duyệt
        /// </summary>
        public int? StatusType { get; set; }
    }
}