// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ProductBlockProduct
    {
        public int ProductBlockProduct_id { get; set; }
        public int ProductBlock_id { get; set; }
        public int Product_id { get; set; }
        public int? Sort { get; set; }

        public virtual ProductBlock ProductBlock_ { get; set; }
    }
}