// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class Province
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
    }
}