// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class QuoteAds
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public string AmountAdsMax { get; set; }
        public string AccessPerWeek { get; set; }
        public string AccessPerMonth { get; set; }
        public decimal? Price { get; set; }
        public string Unit { get; set; }
        public string Note { get; set; }
        public int? Discount { get; set; }
        public string ImageDescriptionWeb { get; set; }
        public string ImageDescriptionApp { get; set; }
        public int? Sort { get; set; }
        public int? Status { get; set; }
    }
}