// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class RegisterPicture
    {
        public int RegisterPicture_ID { get; set; }
        public int? Register_ID { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string ImageSmall { get; set; }
        public string Description { get; set; }
        public DateTime? CreateDate { get; set; }
        public bool? Active { get; set; }
        public int? Sort { get; set; }

        public virtual Register Register_ { get; set; }
    }
}