// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class Register
    {
        public Register()
        {
            RegisterPicture = new HashSet<RegisterPicture>();
        }

        public int Register_ID { get; set; }
        public string Name { get; set; }
        public int? SBD { get; set; }
        public DateTime? Birthday { get; set; }
        public string Birthplace { get; set; }
        public string School { get; set; }
        public string Class { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Facebook { get; set; }
        public string Yahoo { get; set; }
        public double? Hight { get; set; }
        public double? Weight { get; set; }
        public double? Number01 { get; set; }
        public double? Number02 { get; set; }
        public double? Number03 { get; set; }
        public string Hobby { get; set; }
        public string URL { get; set; }
        public DateTime? CreateDate { get; set; }
        public bool? Active { get; set; }

        public virtual ICollection<RegisterPicture> RegisterPicture { get; set; }
    }
}