// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ReplaceChar
    {
        public int ReplaceChar_ID { get; set; }
        public string OldChar { get; set; }
        public string NewChar { get; set; }
    }
}