// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class Resume
    {
        public int Resume_ID { get; set; }
        public string FullName { get; set; }
        public DateTime? DOB { get; set; }
        public bool? Sex { get; set; }
        public string Address { get; set; }
        public int? CareerCategory_ID { get; set; }
        public int? Location_ID { get; set; }
        public int? ProductCateRelate { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Certificate { get; set; }
        public string Image { get; set; }
        public string IdentityNumber { get; set; }
        public string IntroInfomation { get; set; }
        public string ExprienceDescription { get; set; }
        public string JobExpect { get; set; }
        public int? MinSalary { get; set; }
        public string MetaCategory { get; set; }
        public Guid? User_ID { get; set; }
        public Guid? CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public Guid? LastEditBy { get; set; }
        public DateTime? LastEditDate { get; set; }
        public string URL { get; set; }
    }
}