// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class ShoppingCartDetail
    {
        public int Id { get; set; }
        public int ShoppingCartMasterId { get; set; }
        public string ShopingCartCode { get; set; }
        public int ProductId { get; set; }
        public int? Qty { get; set; }
        public decimal? Price { get; set; }
        public decimal? DisCount { get; set; }
        public string Remark { get; set; }
        public int? StatusCart { get; set; }
        public DateTime? CreateDate { get; set; }
        public Guid? CreateBy { get; set; }
        public DateTime? LastEditDate { get; set; }
        public Guid? LastEditBy { get; set; }
        public string ReasonCancel { get; set; }
        public int? IsCancelByBuyer { get; set; }
    }
}