// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class Sitemap
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public int? Sort { get; set; }
        public bool? Active { get; set; }
        public string LanguageID { get; set; }
        public int? ParentID { get; set; }
    }
}