// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class StatsProduct
    {
        public int Id { get; set; }
        public DateTime? ProductCreatedOn { get; set; }
        public string ProductCreatedOnString { get; set; }
        public int? TotalProduct { get; set; }
        public int? TotalProductActive { get; set; }
        public int? TotalProductDeActive { get; set; }
        public int? TotalProductType1 { get; set; }
        public int? TotalProductType2 { get; set; }
        public int? TotalProductType3 { get; set; }
        public int? TotalProductType4 { get; set; }
        public int? TotalProductType5 { get; set; }
        public int? TotalProductType6 { get; set; }
        public int? TotalProductType7 { get; set; }
    }
}