// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class Store
    {
        public int Store_ID { get; set; }
        public int? Style_ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string AboutUs { get; set; }
        public string Keyword { get; set; }
        public string Logo { get; set; }
        public string Banner { get; set; }
        public string BannerExt { get; set; }
        public int? BannerWidth { get; set; }
        public int? BannerHeight { get; set; }
        public string PageBackground { get; set; }
        public string Ad_left { get; set; }
        public string Ad_top { get; set; }
        public string Address { get; set; }
        public int? Location_ID { get; set; }
        public string Map { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string YM { get; set; }
        public string YM2 { get; set; }
        public string Skype { get; set; }
        public string Website { get; set; }
        public string Contact { get; set; }
        public string SupportBuy { get; set; }
        public int? Rank { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public bool? Active { get; set; }
        public int? ArticleTop { get; set; }
        public int? ProductTop { get; set; }
        public string Domain { get; set; }
        public string SubDomain { get; set; }
        public int? Counter { get; set; }
        public Guid? CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public Guid? LastEditBy { get; set; }
        public DateTime? LastEditDate { get; set; }
        public string URL { get; set; }
        public string Tag { get; set; }
    }
}