// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class SysLog
    {
        public Guid SysLog_ID { get; set; }
        public int? SysLogType_ID { get; set; }
        public string Content { get; set; }
        public string QRCodeSecretContent { get; set; }
        public string QRCodePublicContent { get; set; }
        public string SerialNumber { get; set; }
        public int? Product_ID { get; set; }
        public int? Location_ID { get; set; }
        public int? DepartmentMan_ID { get; set; }
        public int? ProductBrand_ID { get; set; }
        public string ProductName { get; set; }
        public string ProductBrandName { get; set; }
        public DateTime? CreateDate { get; set; }
        public Guid? CreateBy { get; set; }
        public DateTime? UsedDate { get; set; }
        public string UsedApplication { get; set; }
        public string UsedLocation { get; set; }
        public string UsedName { get; set; }
        public string UsedAddress { get; set; }
        public string UsedPhone { get; set; }
        public string UsedIdentityCard { get; set; }
        public string StoreName { get; set; }
        public string StoreAddress { get; set; }
    }
}