// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class SystemMessage
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Message { get; set; }
    }
}