// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class Tag
    {
        public Tag()
        {
            TagMap = new HashSet<TagMap>();
        }

        public int Tag_ID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<TagMap> TagMap { get; set; }
    }
}