// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.Models
{
    public partial class TagMap
    {
        public int TagMap_ID { get; set; }
        public int? Tag_ID { get; set; }
        public int? TagType_ID { get; set; }
        public int? Value_ID { get; set; }

        public virtual TagType TagType_ { get; set; }
        public virtual Tag Tag_ { get; set; }
    }
}