// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.ModelsPayment
{
    public partial class DiscountConfig
    {
        public int Discount_ID { get; set; }
        public int? Month { get; set; }
        public decimal? Percent_Discount { get; set; }
        public bool? Status { get; set; }
    }
}