// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.ModelsPayment
{
    public partial class OrderDetail
    {
        public string OrderDetail_ID { get; set; }
        public string Order_ID { get; set; }
        public string ProductName { get; set; }
        public int? ProductBrand_ID { get; set; }
        public string ProductBrandName { get; set; }
        public string Unit { get; set; }
        public int? Quatity { get; set; }
        public decimal? Price { get; set; }
        public decimal? VAT { get; set; }
        public decimal? Sum { get; set; }
        public decimal? DisCount { get; set; }
        public decimal? Total { get; set; }
        public string Description { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string OrderCode { get; set; }
        public string OrderImage { get; set; }
        public int? MonthRemain { get; set; }
        public decimal? TotalDeduct { get; set; }

    }
}