// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.ModelsPayment
{
    public partial class Order
    {
        public string Order_ID { get; set; }
        public int? Service_ID { get; set; }
        public decimal? Sum { get; set; }
        public decimal? DisCount { get; set; }
        public decimal? Total { get; set; }
        public int? Discount_ID { get; set; }
        public int? PaymentType_ID { get; set; }
        public int? PaymentStatus_ID { get; set; }
        public int? ProductBrand_ID { get; set; }
        public string ProductBrandName { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerEmail { get; set; }
        public string SalesUserName { get; set; }
        public string SalesName { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string LastEditBy { get; set; }
        public DateTime? LastEditDate { get; set; }
        public string ApprovedBy { get; set; }
        public DateTime? ApprovedDate { get; set; }
        public string JsonMetaData { get; set; }
        public decimal? VAT { get; set; }
        public string OrderCode { get; set; }    
    }
}