// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.ModelsPayment
{
    public partial class PaymentLog
    {
        public int PaymentLog_ID { get; set; }
        public string Order_ID { get; set; }
        public decimal? Amount { get; set; }
        public int? PaymentStatus_ID { get; set; }
        public int? PaymentType_ID { get; set; }
        public int? ProductBrand_ID { get; set; }
        public string ProductBrandName { get; set; }
        public string UserName { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string BankCode { get; set; }
        public string BankTranNo { get; set; }
        public string CardType { get; set; }
        public string OrderInfo { get; set; }
        public string TransactionNo { get; set; }
        public string ResponseCode { get; set; }
        public string TxnRef { get; set; }
    }
}