// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.ModelsPayment
{
    public partial class PaymentSetting
    {
        public int Id { get; set; }
        public string vnp_Url { get; set; }
        public string vnp_Returnurl { get; set; }
        public string vnpay_api_url { get; set; }
        public string vnp_TmnCode { get; set; }
        public string vnp_HashSecret { get; set; }
        public string vnp_Returnurl_Web { get; set; }
    }
}