// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.ModelsPayment
{
    public partial class PaymentStatus
    {
        public int PaymentStatus_ID { get; set; }
        public string Name { get; set; }
    }
}