// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace HNM.DataNC.ModelsPayment
{
    public partial class PaymentBanking
    {
        public int Id { get; set; }
        public int? PaymentTypeId { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public DateTime? CreateDate { get; set; }
        public Guid? CreateBy { get; set; }
        public DateTime? LastEditDate { get; set; }
        public Guid? LastEditBy { get; set; }
        public string BankLogo { get; set; }
        public string BankInfo { get; set; }
        public string BankNumber { get; set; }
        public string BankReceive { get; set; }
    }
}